name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm || true
      - name: Lint
        run: |
          ruff check .
      - name: Test
        run: |
          pytest --cov=src -q
      - name: Coverage summary
        if: always()
        run: |
          pytest --cov=src --cov-report=term-missing -q || true
